import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // opcional, útil para Tailwind
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} antialiased`}>
        <div className="grid min-h-screen grid-cols-(--grid-cols-app)">
          <aside className="border-r border-zinc-200 py-8 px-4">
            <Sidebar />
          </aside>
          <main className="p-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
